version: '3'
services:
  db:
    image: postgres
    networks:
      - backend
    volumes: 
      - data_base:/var/lib/postgresql/data
  web1:
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${PROTOCOL}://${DB_USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
      - PROXY_URL=proxy:8080
      - WEB_DNS=web1
    links:
      - db

  web2:
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${PROTOCOL}://${DB_USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
      - PROXY_URL=proxy:8080
      - WEB_DNS=web2
    links:
      - db
  
  web3:
    build: .
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=${PROTOCOL}://${DB_USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
      - PROXY_URL=proxy:8080
      - WEB_DNS=web3
    links:
      - db
  
  proxy:
    build:
      context: ./../proxy/
      dockerfile: dockerfile
    networks:
      - frontend
    depends_on:
      - web1
      - web2
      - web3
    ports:
      - "9000:8080"
volumes: 
  data_base:
networks:
  frontend:
  backend:
